version: '3.8'

services:
  front_build:
    container_name: pez_front_builder
    build:
      context: .
      dockerfile: dockerfile.front
    volumes:
      - ./front:/app
  back_build:
    container_name: pez_back_builder
    build:
      context: .
      dockerfile: dockerfile.back
    volumes:
      - ./back:/src
    depends_on:
      front_build:
        condition: service_healthy

  manager:
    container_name: pez_manager
    build:
      context: .
      dockerfile: dockerfile.back
    command: >
      /bin/sh -c "
        echo '=== Start Manager ===' &&
        update-ca-certificates &&
        dotnet run -p /src/UKTMK.Salesportal.Manager.App/UKTMK.Salesportal.Manager.App.csproj --no-build --urls=http://0.0.0.0:80
      "
    ports:
      - "5001:80"
    depends_on:
      back_build:
        condition: service_healthy
    volumes:
      - ./back:/src
      - ./front/build_manager:/src/UKTMK.Salesportal.Manager.App/wwwroot
      - ./files:/srv/filestore
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/pki/ca-trust:/etc/pki/ca-trust:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - /etc/ca-certificates:/etc/ca-certificates:ro
    environment:
      - DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2SUPPORT=false
    networks:
      - proxy_network

  supplier:
    container_name: pez_supplier
    build:
      context: .
      dockerfile: dockerfile.back
    command: >
      /bin/sh -c "
        echo '=== Start supplier ===' &&
        update-ca-certificates &&
        dotnet run -p /src/UKTMK.Salesportal.Supplier.App/UKTMK.Salesportal.Supplier.App.csproj --no-build --urls=http://0.0.0.0:80
      "
    ports:
      - "5002:80"
    depends_on:
      back_build:
        condition: service_healthy
    volumes:
      - ./back:/src
      - ./front/build_supplier:/src/UKTMK.Salesportal.Supplier.App/wwwroot
      - ./files:/srv/filestore
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/pki/ca-trust:/etc/pki/ca-trust:ro
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates:ro
      - /etc/ca-certificates:/etc/ca-certificates:ro
    environment:
      - DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
      - DOTNET_SYSTEM_NET_HTTP_SOCKETSHTTPHANDLER_HTTP2SUPPORT=false
    networks:
      - proxy_network


#   nginx:
#     image: nginx:latest
#     container_name: nginx-proxy
#     restart: always
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx-conf/nginx.conf:/etc/nginx/nginx/conf:ro
#       - ./nginx-conf/conf.d:/etc/nginx/conf.d:ro
#       - ./nginx-conf/certs:/etc/nginx/certs
#       - ./nginx-conf/logs:/var/log/nginx
    # networks:
    #   - proxy_network

networks:
  proxy_network:
    driver: bridge