version: '3.8'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma-data:/app/data
      - ./certs:/usr/local/share/ca-certificates:ro
    ports:
      - "3001:3001"
    restart: unless-stopped
    environment:
      - UPTIME_KUMA_PORT=3001
    command: >
      sh -c "
        update-ca-certificates &&
        node server/server.js
      "
